### PR TITLE
fix(markdown): copying html into markdown

### LINKED ISSUE #7233: Formatting lost when copy-pasting from Google Docs to markdown widget
**Describe the bug**

Formatting such as bold text, headings, links etc. are lost when copy pasting from a word processor such as Google Docs.

Here is the behavior from Netlify CMS 2.15.72:

https://github.com/decaporg/decap-cms/assets/8106669/eec07104-8d31-418e-9277-13bdcc62c472

**To Reproduce**

Copy formatted text from a word processor and paste it into a markdown widget with "Rich text" selected:

https://github.com/decaporg/decap-cms/assets/8106669/a995e244-576b-4429-8a43-34052fa081fe

**Expected behavior**

The formatting remains and is converted to markdown.

**Screenshots**

See recordings above.

**Applicable Versions:**

 - Decap CMS version:
   - decap-cms-app 3.1.10
   - decap-cms-core 3.3.6
 - Git provider: GitHub
 - OS: Linux
 - Browser version Firefox 125.0b6

 - Node.JS version: n/a

**CMS configuration**

n/a

**Additional context**

Happy to make an attempt with a PR to fix this if you can point me to the code :)

### PR DESCRIPTION
**Pull request by hip3r**
closes #7233 

**Summary**

When pasting html into markdown, keep styles instead of plain text.
Code copied from official example https://github.com/ianstormtaylor/slate/blob/main/site/examples/ts/paste-html.tsx

**Test plan**

image
image

**Checklist**

Please add a `x` inside each checkbox:

- [x] I have read the [contribution guidelines](https://github.com/decaporg/decap-cms/blob/main/CONTRIBUTING.md).

**A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Comment by mattcen** [comment]
Nice work on this! Just build a version with this merged in and it coped fine with the simple Google Doc I threw at it! Thanks for your efforts!

File: packages/decap-cms-widget-markdown/src/MarkdownControl/plugins/html/withHtml.js [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+  H6: () => ({ type: 'heading-six' }),
+  IMG: el => ({ type: 'image', url: el.getAttribute('src') }),
+  LI: () => ({ type: 'list-item' }),
+  OL: () => ({ type: 'numbered-list' }),
+  P: () => ({ type: 'paragraph' }),
+  PRE: () => ({ type: 'code' }),
+  UL: () => ({ type: 'bulleted-list' }),
+};
+
+// COMPAT: `B` is omitted here because Google Docs uses `<b>` in weird ways.
```
Comment (mattcen) [inline packages/decap-cms-widget-markdown/src/MarkdownControl/plugins/html/withHtml.js:21]: Except on line 29, `B` is, in fact, not omitted. Should the comment, or the `B` mapping be removed?

Comment (hip3r) [reply packages/decap-cms-widget-markdown/src/MarkdownControl/plugins/html/withHtml.js:22]: great catch.
Slate also noticed and updated this, so I just copied new version of example.

> Should the comment, or the B mapping be removed?

Since it's known that Google Docs uses `<b>` differently, I would leave it removed as is

**Review by demshy — APPROVED** [review]
